### ISSUE TITLE
能否做成socks或者http proxy

### ISSUE THREAD

**Issue by woyaojizhu8** [firesh/dns#1]
还是感觉用浏览器上切换代理的扩展，比如proxy switch omega 等切换代理来得方便。不仅可以设定规则，还可以随时添加当前网站到规则中。我目前是本地开了一个 cent os 虚拟机 ，里面设定dnsmasq规则（把所有域名都解析到反代），然后主机ssh -D 连上去，作为socks5 proxy使用。如果可以像本项目这样用docker来实现就更好了。

**Comment by firesh** [comment]
代理方式在浏览器里面切换确实会方便一些。
方便的话提供一下具体的搭建命令，我可以让它docker化。

**Comment by woyaojizhu8** [comment]
我水平有限，还做不到几条命令就实现这个功能。。。我是在cent os 虚拟机的dnsmasq配置文件里加上address=/#/x.x.x.x（x.x.x.x即反代的ip地址），然后  chattr +i /etc/resolv.conf,  最后主机ssh -D 连接到虚拟机，浏览器代理扩展设置socks5 proxy 地址。

**Comment by woyaojizhu8** [comment]
研究了一下docker，目前我已经实现用一个基于ubuntu 15.04 的镜像，把sniproxy 转成socks5 proxy使用，但是每次都要在容器里手动启动dnsmasq 和ssh服务，还要手动 ssh -D 连上去。不知有何简化的办法

**Comment by firesh** [comment]
有代码码，启动的命令，只要放到Dockerfile的CMD 里面就好了。

**Comment by woyaojizhu8** [comment]
@firesh 那每次要ssh -D连上去，怎么自动进行呢？
